### ISSUE TITLE
latest update breaks some things

### ISSUE THREAD

**Issue by nascentt** [luketimothyjones/YouTube-Spam-Remover#2]
hi let me prefix this with - I love this addon it's the only youtube comment improvement addon that's actually worked for me.
That being said, this latest update has led to all avatars being blurred, all of them.
And also video authors are now marked as spam due to "[copycat avatar]" despite being the legitimate author.

example video's comments video:https://www.youtube.com/watch?v=TXkS5ew5S3k (although it seems true for all videos i check) 
![sshot-2023-02-17-21-04-01](https://user-images.githubusercontent.com/1145722/219793081-59e66c25-cb7c-4dd5-bb72-c9e353321735.png)

**Comment by samipfjo** [comment]
Uh-oh! Could you confirm for me which version of the extension you are using? Version 2.0.0 is bugged but I pushed out a patch yesterday.

On Firefox: Extensions > Manage extensions > three dots next to YTSR > manage > version (scroll down a little)
On Chrome: Extensions > Manage extensions > the number by "YouTube Spam Remover"

**Comment by samipfjo** [comment]
If you are on version 2.0.0, please update the extension and let me know it that fixes it.

I can't replicate this on the video you shared in Chrome or Firefox on 2.0.1, so it'll be _very concerning_ if it's still exhibiting this behavior.

If you're on 2.0.1:
First, try visiting the video and pressing Ctrl+Shift+R (Windows) or Cmd+Shift+R (macOS). This makes the browser reload the page from scratch and should fix any weirdness that might have occurred due to the version change.

If that doesn't fix it, please share the following:
- Browser (Firefox/Chrome/etc) and browser version (changes how many things are processed)
- Operating system (changes default style sheets, which can change how custom styles are applied)

**Comment by samipfjo** [comment]
I just pushed out 2.0.2 which will force the extension to reload once it's installed. Hopefully that fixes the issue for folks.

**Comment by samipfjo** [comment]
I was finally able to replicate the video author comments being marked as copycats and have patched it. It'll be fixed once 2.0.3 is approved.

**Comment by nascentt** [comment]
My appologies for the radio silence, I just realised I had a rule that was removing github emails from my inbox and had disabled this addon due to the issue so didn't see it get updated.

I can confirm I no longer see this issue many thanks for fixing.  Appologies for the year delay in responding.
