### ISSUE TITLE
Monstercat marked as spam for copycat avatar

### ISSUE THREAD

**Issue by miku4k** [luketimothyjones/YouTube-Spam-Remover#3]
Specifically [this comment](https://www.youtube.com/watch?v=4Tdu6IIikd0&lc=Ugyh6irQTpdDV-Q83-Z4AaABAg) under [this video](https://www.youtube.com/watch?v=4Tdu6IIikd0). The comment isn't pinned but is by the video author. I can't find any other instances of this happening, partially because I can't find any unpinned comments by Monstercat.
I am using Firefox 116 and YTSR 2.0.3.

Screenshot:
![image](https://github.com/lukepfjo/YouTube-Spam-Remover/assets/89653242/7c6e47f3-e1a1-4742-bdb0-14471bcb10df)

**Comment by miku4k** [comment]
Looks like it was a fluke, I reloaded, and now it's fine. I tried reloading before posting this but it stayed when I did.

**Comment by samipfjo** [comment]
Just reproduced this, thank you for letting me know.

There's a specific check to allow-list the video poster which must be failing, I'll get a patch out ASAP.

**Comment by samipfjo** [comment]
Okay, bug squashed, pushing the update out now. The Firefox and Chrome teams will need to approve the update, but that's usually pretty quick. 

Explanation:

This happened due to a workaround for channels that had yet to move over to the new style channel `@handle`.

I hadn't accounted for mismatches between the channel name and their handle, in this case `Monstercat Uncaged` and `@Monstercat` respectively. The comment that's getting flagged is also by `@Monstercat`, but it bears the mainline channel name `Monstercat` rather than `Monstercat Uncaged`.

Unfortunately this will continue to happen in the (hopefully rare) case of an author having multiple channels that use the same image and commenting cross-channels, but there's nothing that can feasibly be done to fix that case without removing copycat protection entirely.

**Comment by samipfjo** [comment]
Well, that's what having email notifications off for reviews on the Chrome Web Store gets me. Seeing a couple of negative reviews that got posted would have made me catch this earlier.

Again, thank you so much for submitting this. It may have been a while before I noticed it myself.

**Comment by miku4k** [comment]
Thanks for fixing this, I'm glad I could help.
